### ISSUE TITLE
Headless Task is not working

### ISSUE THREAD

**Issue by denisraison** [transistorsoft/nativescript-background-fetch#10]
### Your Environment
Plugin version: 1.2.0
Platform: Android
OS version: API VERSION 24
Device manufacturer / model: Emulator (Nexus 5)
Plugin config:
```
        ...
        import { BackgroundFetch } from "nativescript-background-fetch"
        ...
        BackgroundFetch.configure({
        minimumFetchInterval: 15, // minutes

        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
      }, () => {
        console.log("[js] BackgroundFetch event received")
        console.log(BackgroundFetch.headlessTask)
        BackgroundFetch.finish(BackgroundFetch.FETCH_RESULT_NEW_DATA)
      }, status => console.log('BackgroundFetch not supported by your OS', status))

      BackgroundFetch.start(() => {
        console.log("BackgroundFetch successfully started")
      }, (status) => {
        console.log("BackgroundFetch failed to start: ", status)
      })

      if (app.android) {
        const cb = async () => {
          console.log('[My BackgroundFetch HeadlessTask] onFetch')
          BackgroundFetch.finish()
        }
        BackgroundFetch.registerHeadlessTask(cb)
        console.log(BackgroundFetch.headlessTask)
        console.log("HeadlessTask registered")
      }
```

### Context

Hi guys, firtly thanks for the pluging it's awesome.
I just want to know if I'm doing something wrong here.

I'm running the code showed above and awayays when I run the command:
adb shell cmd jobscheduler run -f <your.application.id> 999
or even:
adb shell am broadcast -a <your.application.id>.event.BACKGROUND_FETCH

I'm getting that I have not defined my headlessTask.

> '[BackgroundFetch] invokeHeadlessTask ERROR - headlessTask is null.  Did you BackgroundFetch.registerHeadlessTask(myTask) in your app.ts?'

I'm not really sure what to do here, I've even put a log just before call the bit of code and my **this.headlessTask** is really undefined.
Looks like it's creating another intance of the class and losing the content for the this.headlessTask property.

Does anyone had a similar problem yet?

Thank you,
Denis

**Comment by Prabhuthirunavukkarasu** [comment]
@denisraison we are travelling in same ship....I'm getting that error too. please let me know if you have any solution.Thanks

**Comment by denisraison** [comment]
Hey @Prabhuthirunavukkarasu the solution was to call the registerHeadlessTask on the startup (main) module in my case **app.js**.

So the module will look something like that:

```
import { BackgroundFetch } from "nativescript-background-fetch"
...

if (app.android) {
    BackgroundFetch.registerHeadlessTask(function () {
        console.log("CALLED HEADLESS TASK")
        console.log("Do your stuff...")
  })
}
```

**Comment by Prabhuthirunavukkarasu** [comment]
Thanks a lot . Now, its working fine @denisraison

**Comment by christocracy** [comment]
As stated in docs for Headless.

**Comment by ashokIosDev** [comment]
Hi @denisraison @christocracy  Headlesstask work in ios?

**Comment by ashokIosDev** [comment]
and how to test headlesstask

**Comment by christocracy** [comment]
It's all there in the [README](https://github.com/transistorsoft/nativescript-background-fetch#debugging)

**Comment by ashokIosDev** [comment]
> It's all there in the [README](https://github.com/transistorsoft/nativescript-background-fetch#debugging)

when i try those commands those are executing background fetch only, i need for headlesstask
i keep localnotification and try to fire that one in headlesstask after app termination but not working

**Comment by ashokIosDev** [comment]
sorry for somany questions @christocracy background fetch work when in foreground in ios? 
2. in android headlesstask work periodically if app is terminated or only one time?
