### ISSUE TITLE
How to display notification?

### ISSUE THREAD

**Issue by jibon57** [transistorsoft/nativescript-background-fetch#7]
Hello,

Thanks for the plugin. How can I display notification of new information? 

Thanks

**Comment by christocracy** [comment]
That’s up to you.  This plugin is not involved with UI.  It merely fires an event where you’re free to do anything you desire.

**Comment by jibon57** [comment]
OK understand, but any hits for Android?

**Comment by christocracy** [comment]
Have you tried asking Google?
